@server = http://localhost:8080

### get
GET {{server}}/api

### post valid
POST {{server}}/api
content-type: application/json

{
    "message": "Like && Subscribe 🌹"
}

### post invalid
POST {{server}}/api
content-type: application/json

{
    "massage": "Like && Subscribe 🌹"
}
